    const dizionario = {
        deorum: "I Mani sono gli spiriti dei defunti nell'antica religione romana.",
        Ippolito: "Ippolito Pindemonte è il destinatario della poesia 'I Sepolcri' di Ugo Foscolo.",
        domandaRetorica: "domanda retorica tendente alla negazione.",
        aspettative: "non si offrivano all'aspettativa del poeta",
        amico: "Pindemonte",
        mesta: "ispirazione malinconica",
        muse: "elevatezza dell'ispirazione e valore purificai della poesia",
        sepolcri: "Non c'è speraznza di sopravvivenza dopo la morte",
        notte: "Cancella ogni traccia della vita terrena",
        moto: "Visione materialisrtica di Foscolo",
        tempo: "Il tempo distrugge e trasforma tutto",
        dite: "Dite è Plutone, dio degli inferi nella mitologia romana e per metonima indica il regno dei morti.",
        giorno: "mondo della luce, degli esseri viventi",
        suoi: "L'uomo si illude di non morire del tutto se rimane nei ricordi dei suoi cari.",
        celeste: "Corrispondenza affettica che da agli uomini una forma di immortalità simile a quella degli dei.",
        arbore: "latinismo per albero, simbolo di vita e di continuità.",
        consoli: "Morire è come ritornare al grembo materno della natura.",
        sol: "Persona arida e malvagia che non potrà sopravvivere nel ricordo",
        esequie: "se cerca di immaginare ciò che sarà lui dopo la morte.",
        acherontei: "eco del 'de rerum natura' di Lucrezio, il fiume Acheronte è il confine tra il mondo dei vivi e quello dei morti. Per sineddoche rappresenta l'inferno",
        iddio: "cioè può pensare di essere dannato o salvato.",
        natura: "Dalla tombra sembra uscire ik sospiro del defunto che esprime il desiderio di sopravvivere.",
        contende: "Parla dell'editto di Saint-Cloud del 1804 che vieta le sepolture nei centri abitati.",
        talia: "Parini è sacerdote di Talia, la musa della commedia, e quindi rappresenta la poesia come un'arte che consola.",
        sardanapalo: "la musa inspirava l'ironia e la satira di Parini, che si opponeva alla vita dissoluta e al lusso della nobiltà. Sardanapalo era un re assiro leggendario, simbolo di vita dissoluta e di decadenza.",
        nume: "Jacopo Ortis incontra Parini in un boschetto di tigli.",
        tiglio: "Jacopo Ortis incontra Parini in un boschetto di tigli.",
        parini: "contrapposizione tra il capo sacro del poeta e i tumuli plebei.",
        evirato: "Parini ha fatto una ode importante: l'evirazoine dei cantanti/la musica.",
        ossa: "Parini fu sepolto in una fossa comune, senza un vero sepolcro.",
        upupa: "era erronemanete un uccello notturno e luttuoso",
        sepolture: "descrizione che riptoduce il gusto lugubre della prsia pre-romantica",
        indarno: "La rugiada viene vista cone un pianto che conforta la sepoltura",
        are:  "altari",
        vivi: "soggetti di toglieano",
        destina: "il rispetto per i morti è un dovere dei vivi ed è un fondamento della società civile. Concetto che verra ripreso da Giambattista Vico.", 
        figli: "i defunti veniavno venerati come gli dei",
        giuramento: "Esempi della funzione civile dei sepolcri: i giuramenti venivano fatti sui sepolcri dei padri, i testamenti venivano depositati nei sepolcri.",
        religion: "intorno al culto dei morti si concentrano tutti i valori di una civilta.",
        sassi: "I sepolcri sono i sassi che coprono le tombe, simbolo della memoria dei defunti.",
        scheletri: "Pitture e sculre che ricorndano che tuttiqui monumenti sono destinati a morire",
        madri: "Foscolo esamina gli effetti psicologici dell'idea della morte nella societa cristiana.",
        effluvi: "Il poeta si rivolge ai defunti, chiedendo loro di non disperdere i loro effluvi, cioè le loro essenze.",
        preziosi: "si credeva che i vasi lacrimali tr",
        rapian: "uso di porre nelle tombe e quando mi alleno.",
        amaranti: "Pianta a forma di spiga di colore rosso scuro.",
        sedea: "secondo l'uso rituale antico.",
        elisi: "si ricollega ai campi Elisi",
        bara: "bisogna di una bara per seppellire i morti.",
        orco: "orco è un termine che indica l'inferno o il regno dei morti pagani.",
        monumenti: "le tombe no sono esempi di virtu civiele",
        dotto: "uno dei tre titoli.",
        amista: "amicizia",
        esempio: "Foscolo contrappone la propria figura da uomo libero e colto a quella di un uomo comune, che non ha la stessa cultura e sensibilità.",
        egregie: "Foscolo propone le tombe di Santa Croce a Firenze",
        vidi: "inno a Firenze e alle glorie italiche",
        sfronde: "priva di potere regale",
        lagrime: "Parla di Machiavelli",
        arca: "Parla di Michelangelo",
        padiglion: "Parla di Galielo",
        aure: "",
        gridai: "Verbo principale",
        prima: "parla di Dante",
        cari: "parla di Petrarca",
        amore: "distinzione tra venere celeste e venere terrena",
        beata: "Il vanto di avere questi grandi uomini sepolti in Italia e di aver dato i natali a Dante e Petrarca.",
        intelletti: "Visione patriottica di Foscolo, che vede l'Italia come un luogo di grandi intelletti e cultura.",
        Vittorio: "usa il nome perché si rivede nelle sue idee",
        Irato: "Alfieri era irato perché gli dei sono indifferenti alla degradazione dell'Italia.",
        speranza: "speranza di una rinascita dell'Italia.",
        ah: "Foscolo collega le tombe a Santa Croce con la battaglia di Maratona.",
        navigante: "Da questopunto inizia il discorso riguardo  alla battaglia di Maratona.",
        parche: "il canto delle Parche, le dee del destino, che tessono il filo della vita degli uomini, profetizza il destino degli uomini.",
        felice: "passaggio logico che collega la battaglia di Maratona con la speranza di una rinascita dell'Italia mediante il sentimento patriottico.",
        antenna: "albero che regge le vele.",
        udisti: "un'immagine simile si trova nell'ode 'all'Amica risanata'",
        retee: "le rive del promontorio Reteo, vicino a Troia.",
        aiace: "Alla morte di Achille, le sue armi dovevano essere ereditate da Aiace ma Ulisse le ottenne grazie alla sua astuzia. Successivamente Aiace impazzì e si suicidò. Mentre Ulisse tornava ad Itaca una tempesta lo fece naufragare e le onde riportarono le armi di Achile alla tomba di Aiace.",
        generosi: "Anche se in vita non vengono riconosciuti i meriti, in morte quest'ultima deve essere giusta per tutti",
        senno: "Astuzia di Ulisse.",
        regi: "Agamennone e Menelao.",
        spoglie: "per ottenerle bisognava essere guerrieri valorosi.",
        tempi: "sfavorevoli agli animi generosi e amanti della libertà",
        animatrici: "passaggio logico che collega la vicenda di Aiace con  il desiderio di Foscolo di cantare gli eroi come aveva fatto Omero.",
        siedon: "Le muse sono dette .pimplee perché si dice che vivano sul monte Pimpla, in Tessaglia.",
        assaraco: "padre di Anchise, il padre di Enea.",
        talami: "letti matrimoniali",
        giulia: "l'impero romano era stato fondato da Giulio Cesare che faceva parte della gens Iulia che origine con la fuga dalla citta di Toria.",
        la: "Atropo che tronca il filo della vita",
        volontà: "non le consente l'immortalità",
        ambrosia: "nettare degli dei.",
        erittonio: "figlio di Dardano.",
        ilo: "Figlio di Erittonio.",
        iliache: "da Ilio, la rocca di Troia.",
        indarno: "presto troia sarebbe caduta.",
        cassandra: "figlia di Priamo che aveva il dono della profezia ma nessuno le credeva.",
        giovanotti: "Cassandra profetizza il tiste destino della città ed educa i giovani.",
        Argo: "La Grecia è indicaa con la citta con cui re è Agamennone.",
        scure: "abbattere",
        mendico: "un mendico è un povero che chiede l'elemosina.",
        cavalli:  "rendere gli schiavi liberi",
        antiche: "Tombe che Omero visita",
        urne: "vasi contenenti le ceneri dei progeenitori.",
        antri: "tombe sotteranee",
        due: "da Ecole alle Amazzoni",
        pelidi: "Achille, figlio di Peleo e suo figlio Pirro.",
        vate: "Omero ha una funzione poetica sacra.",
        oceano: "Grande fiume che circonda il mondo, simbolo di eternità.",
        ettore: "Il poeta eternera i grandi eroi della guerra di Troia, come Ettore, Achille e Omero stesso. Non importa se sono i vinti o i vincitori, ciò che conta è il loro valore.",
    };

    const parole = document.querySelectorAll('.interagibili');

    parole.forEach(parola => {
      parola.addEventListener('click', () => {
        const chiave = parola.getAttribute('data-key');
        const definizione = dizionario[chiave] || "Definizione non trovata.";
        document.getElementById('output').textContent = definizione;
      });
    });